### ISSUE TITLE
Error in variance == 0 when a group only has n of 1.

### ISSUE THREAD

**Issue by mkshaw** [mkshaw/r2mlm#26]

**Comment by mhimmelstein** [comment]
I had come here to raise having run into this issue. It looks like the solution has been found, but not pushed out yet, is that correct (I checked the development version too)? 

I was able to tweak the function code for r2mlm_lmer() as a hack to get it to work, but I'm using this to teach an HLM class and don't know if I can have my students do that independently. 

Thanks for the awesome package!

**Comment by mkshaw** [comment]
Hello! That's correct: I think I've fixed it, but haven't uploaded the fixed version to CRAN (since I'm also trying to fix other bugs before I release a new version). I also haven't pushed to the main branch on github; it's on the refactoring branch. When you say you checked the development version, do you mean you tried with the `devtools::install_github("mkshaw/r2mlm", ref = "refactoring")` package (running `library(r2mlm)` again after installing that development version) and you still ran into an issue?

**Comment by mhimmelstein** [comment]
Ah, that makes sense. I just used the main development branch, not `ref = "refactoring"`. I can try that too. Thank you!

And we already did incorporate it! I'm the lab instructor/TA and the primary instructor wanted to teach the Rights and Sterba papers for how to think about HLM effect sizes. We actually started using it a bit right before you pushed it to CRAN :). It's been super helpful for producing tangible examples.

**Comment by mkshaw** [comment]
Let me know how the `ref = "refactoring"` goes, and I'm really glad it's been helpful so far (bugs notwithstanding)!

**Comment by mhimmelstein** [comment]
I checked the refactoring branch, and the base `r2mlm()` function does indeed work, but the bug is still present in `r2mlm_comp()`

**Comment by mkshaw** [comment]
This is actually great news! I haven't fixed `r2mlm_comp()` yet, so I would expect it to not work.

**Comment by mhimmelstein** [comment]
Great! I'll keep an eye out for when the next update pushes out. Thanks again for all the hard work!

**Comment by mkshaw** [comment]
Fixed in 2bb041a8fcfea37576620f3d3d1492031d2818f6.
